---
title: k-Abelian Complexity of Tribonacci sequence from 1 to 5
date: '2025-02-23'
format:
  html:
    code-fold: false
    embed-resources: true
    toc: true
    toc-location: left
    number-sections: true
    syntax-definitions: 
        - walnut.xml
  ipynb: default 
execute:
  cache: true
  keep-ipynb: true
  allow_errors: true
jupyter: walnut
---

## Initial Numeration System Setup

First we define the subsitution, its numeration system and its fixpoint sequence.

```{walnut}
%%python
from licofage.kit import *
import os
setparams(True, True, os.environ["WALNUT_HOME"])

s = subst('01/02/0')
ns = address(s, "tri")
ns.gen_ns()
ns.gen_word_automaton()
```

Then we setup a factor comparison predicate in Walnut and a first factor occurence predicate.

```{walnut}
def cut "?msd_tri i<=u & j<=v & u+j=v+i & u<n+i & v<n+j":
def feq_tri "?msd_tri ~(Eu,v $cut(i,j,n,u,v) & Tri[u]!=Tri[v])":
eval comp_tri n "?msd_tri Aj $feq_tri(i,j,n) => i<=j":
```


From there we can define the boundary condition `bordercond`, as explained in Fici-Puzynina-2023 section 8.1.

```{walnut}
def bordercond "?msd_tri (k<=n => $feq_tri(i,j,k-1)) & (n<k => $feq_tri(i,j,n))":
```

## 1-abelian complexity

Define the 1-block map of tri and construct the conversion predicate between both numeration systems.

```{walnut}
%%python
s1 = s
ns1 = ns
```

### Compute Parikh vectors

First we compute the Parikh vectors for the prefixes of Tri.

```{walnut}
%%python
for (i,a) in enumerate(ns1.alpha):
    w = {'_': 0}
    w[a] = 1
    parikh = address(s1, ns1.ns, **w)
    (parikh - ns1).gen_dfa(f"trib1p{i}")
```

### Compute the complexity function

Use Walnut to generate a linear representation for the 1-abelian complexity.

```{walnut}
def fac0 "?msd_tri Ex,y $trib1p0(i,x) & $trib1p0(i+n,y) & z+x=y":
def fac1 "?msd_tri Ex,y $trib1p1(i,x) & $trib1p1(i+n,y) & z+x=y":
def fac2 "?msd_tri Ex,y $trib1p2(i,x) & $trib1p2(i+n,y) & z+x=y":
```

```{walnut}
def min0 "?msd_tri Ei $fac0(i,n,x) & Aj,y $fac0(j,n,y) => y>=x":
def min1 "?msd_tri Ei $fac1(i,n,x) & Aj,y $fac1(j,n,y) => y>=x":
def min2 "?msd_tri Ei $fac2(i,n,x) & Aj,y $fac2(j,n,y) => y>=x":
```

```{walnut}
def diff0 "?msd_tri Ex,y $min0(n,x) & $fac0(i,n,y) & z+x=y":
def diff1 "?msd_tri Ex,y $min1(n,x) & $fac1(i,n,y) & z+x=y":
def diff2 "?msd_tri Ex,y $min2(n,x) & $fac2(i,n,y) & z+x=y":
```

```{walnut}
def abeq_tri1 "?msd_tri (Ez $diff0(i,n,z) &  $diff0(j,n,z)) & (Ez $diff1(i,n,z) &  $diff1(j,n,z)) & (Ez $diff2(i,n,z) &  $diff2(j,n,z))":
```

```{walnut}
eval comp_tri1 n "?msd_tri Aj $abeq_tri1(i,j,n) => i<=j":
```


### Apply the semigroup trick

```{walnut}
%SGT comp_tri1 msd_tri Comp_tri1
```

## 2-abelian complexity

Define the 2-block map of tri and construct the conversion predicate between both numeration systems.

```{walnut}
%%python
s2 = block(s, 2)
ns2 = address(s2, "trib2")
ns2.gen_ns()
(ns-ns2).gen_dfa("conv_tri_trib2")
```

Translate the border condition predicate into the current numeration system.

```{walnut}
def bordercond2 "?msd_trib2 (?msd_tri Eii,jj,kk,nn 
($conv_tri_trib2(?msd_tri ii, ?msd_trib2 i) & 
$conv_tri_trib2(?msd_tri jj, ?msd_trib2 j) & 
$conv_tri_trib2(?msd_tri kk, ?msd_trib2 k) & 
$conv_tri_trib2(?msd_tri nn, ?msd_trib2 n) & 
$bordercond(ii,jj,kk,nn)))":
```

### Compute Parikh vectors

First we compute the Parikh vectors for the prefixes of Trib2.

```{walnut}
%%python
for (i,a) in enumerate(ns2.alpha):
    w = {'_': 0}
    w[a] = 1
    parikh = address(s2, ns2.ns, **w)
    (parikh - ns2).gen_dfa(f"trib2p{i}")
```

### Compute the complexity function

Use Walnut to generate a linear representation for the 2-abelian complexity.

```{walnut}
def fac0 "?msd_trib2 Ex,y $trib2p0(i,x) & $trib2p0(i+n,y) & z+x=y":
def fac1 "?msd_trib2 Ex,y $trib2p1(i,x) & $trib2p1(i+n,y) & z+x=y":
def fac2 "?msd_trib2 Ex,y $trib2p2(i,x) & $trib2p2(i+n,y) & z+x=y":
def fac3 "?msd_trib2 Ex,y $trib2p3(i,x) & $trib2p3(i+n,y) & z+x=y":
def fac4 "?msd_trib2 Ex,y $trib2p4(i,x) & $trib2p4(i+n,y) & z+x=y":
```

```{walnut}
def min0 "?msd_trib2 Ei $fac0(i,n,x) & Aj,y $fac0(j,n,y) => y>=x":
def min1 "?msd_trib2 Ei $fac1(i,n,x) & Aj,y $fac1(j,n,y) => y>=x":
def min2 "?msd_trib2 Ei $fac2(i,n,x) & Aj,y $fac2(j,n,y) => y>=x":
def min3 "?msd_trib2 Ei $fac3(i,n,x) & Aj,y $fac3(j,n,y) => y>=x":
def min4 "?msd_trib2 Ei $fac4(i,n,x) & Aj,y $fac4(j,n,y) => y>=x":
```

```{walnut}
def diff0 "?msd_trib2 Ex,y $min0(n,x) & $fac0(i,n,y) & z+x=y":
def diff1 "?msd_trib2 Ex,y $min1(n,x) & $fac1(i,n,y) & z+x=y":
def diff2 "?msd_trib2 Ex,y $min2(n,x) & $fac2(i,n,y) & z+x=y":
def diff3 "?msd_trib2 Ex,y $min3(n,x) & $fac3(i,n,y) & z+x=y":
def diff4 "?msd_trib2 Ex,y $min4(n,x) & $fac4(i,n,y) & z+x=y":
```

```{walnut}
def abeq_trib2 "?msd_trib2 $bordercond2(i,j,2,n+1) & (Ez $diff0(i,n,z) &  $diff0(j,n,z)) & (Ez $diff1(i,n,z) &  $diff1(j,n,z)) & (Ez $diff2(i,n,z) &  $diff2(j,n,z)) & (Ez $diff3(i,n,z) &  $diff3(j,n,z)) & (Ez $diff4(i,n,z) &  $diff4(j,n,z))":
def abeq_tri2 "?msd_tri (n<1 & $feq_tri(i,j,n)) | (n>=1 & (?msd_trib2 Eii,jj,nn ($conv_tri_trib2(?msd_tri i, ?msd_trib2 ii) & $conv_tri_trib2(?msd_tri j, ?msd_trib2 jj) & $conv_tri_trib2(?msd_tri n, ?msd_trib2 nn) & $abeq_trib2(ii,jj,nn-1))))":
```

```{walnut}
eval comp_tri2 n "?msd_tri Aj $abeq_tri2(i,j,n) => i<=j":
```


### Apply the semigroup trick

```{walnut}
%SGT comp_tri2 msd_tri Comp_tri2
```

## 3-abelian complexity

Define the 3-block map of tri and construct the conversion predicate between both numeration systems.

```{walnut}
%%python
s3 = block(s, 3)
ns3 = address(s3, "trib3")
ns3.gen_ns()
(ns-ns3).gen_dfa("conv_tri_trib3")
```

Translate the border condition predicate into the current numeration system.

```{walnut}
def bordercond3 "?msd_trib3 (?msd_tri Eii,jj,kk,nn 
($conv_tri_trib3(?msd_tri ii, ?msd_trib3 i) & 
$conv_tri_trib3(?msd_tri jj, ?msd_trib3 j) & 
$conv_tri_trib3(?msd_tri kk, ?msd_trib3 k) & 
$conv_tri_trib3(?msd_tri nn, ?msd_trib3 n) & 
$bordercond(ii,jj,kk,nn)))":
```

### Compute Parikh vectors

First we compute the Parikh vectors for the prefixes of Trib3.

```{walnut}
%%python
for (i,a) in enumerate(ns3.alpha):
    w = {'_': 0}
    w[a] = 1
    parikh = address(s3, ns3.ns, **w)
    (parikh - ns3).gen_dfa(f"trib3p{i}")
```

### Compute the complexity function

Use Walnut to generate a linear representation for the 3-abelian complexity.

```{walnut}
def fac0 "?msd_trib3 Ex,y $trib3p0(i,x) & $trib3p0(i+n,y) & z+x=y":
def fac1 "?msd_trib3 Ex,y $trib3p1(i,x) & $trib3p1(i+n,y) & z+x=y":
def fac2 "?msd_trib3 Ex,y $trib3p2(i,x) & $trib3p2(i+n,y) & z+x=y":
def fac3 "?msd_trib3 Ex,y $trib3p3(i,x) & $trib3p3(i+n,y) & z+x=y":
def fac4 "?msd_trib3 Ex,y $trib3p4(i,x) & $trib3p4(i+n,y) & z+x=y":
def fac5 "?msd_trib3 Ex,y $trib3p5(i,x) & $trib3p5(i+n,y) & z+x=y":
def fac6 "?msd_trib3 Ex,y $trib3p6(i,x) & $trib3p6(i+n,y) & z+x=y":
```

```{walnut}
def min0 "?msd_trib3 Ei $fac0(i,n,x) & Aj,y $fac0(j,n,y) => y>=x":
def min1 "?msd_trib3 Ei $fac1(i,n,x) & Aj,y $fac1(j,n,y) => y>=x":
def min2 "?msd_trib3 Ei $fac2(i,n,x) & Aj,y $fac2(j,n,y) => y>=x":
def min3 "?msd_trib3 Ei $fac3(i,n,x) & Aj,y $fac3(j,n,y) => y>=x":
def min4 "?msd_trib3 Ei $fac4(i,n,x) & Aj,y $fac4(j,n,y) => y>=x":
def min5 "?msd_trib3 Ei $fac5(i,n,x) & Aj,y $fac5(j,n,y) => y>=x":
def min6 "?msd_trib3 Ei $fac6(i,n,x) & Aj,y $fac6(j,n,y) => y>=x":
```

```{walnut}
def diff0 "?msd_trib3 Ex,y $min0(n,x) & $fac0(i,n,y) & z+x=y":
def diff1 "?msd_trib3 Ex,y $min1(n,x) & $fac1(i,n,y) & z+x=y":
def diff2 "?msd_trib3 Ex,y $min2(n,x) & $fac2(i,n,y) & z+x=y":
def diff3 "?msd_trib3 Ex,y $min3(n,x) & $fac3(i,n,y) & z+x=y":
def diff4 "?msd_trib3 Ex,y $min4(n,x) & $fac4(i,n,y) & z+x=y":
def diff5 "?msd_trib3 Ex,y $min5(n,x) & $fac5(i,n,y) & z+x=y":
def diff6 "?msd_trib3 Ex,y $min6(n,x) & $fac6(i,n,y) & z+x=y":
```

```{walnut}
def abeq_trib3 "?msd_trib3 $bordercond3(i,j,3,n+2) & (Ez $diff0(i,n,z) &  $diff0(j,n,z)) & (Ez $diff1(i,n,z) &  $diff1(j,n,z)) & (Ez $diff2(i,n,z) &  $diff2(j,n,z)) & (Ez $diff3(i,n,z) &  $diff3(j,n,z)) & (Ez $diff4(i,n,z) &  $diff4(j,n,z)) & (Ez $diff5(i,n,z) &  $diff5(j,n,z)) & (Ez $diff6(i,n,z) &  $diff6(j,n,z))":
def abeq_tri3 "?msd_tri (n<2 & $feq_tri(i,j,n)) | (n>=2 & (?msd_trib3 Eii,jj,nn ($conv_tri_trib3(?msd_tri i, ?msd_trib3 ii) & $conv_tri_trib3(?msd_tri j, ?msd_trib3 jj) & $conv_tri_trib3(?msd_tri n, ?msd_trib3 nn) & $abeq_trib3(ii,jj,nn-2))))":
```

```{walnut}
eval comp_tri3 n "?msd_tri Aj $abeq_tri3(i,j,n) => i<=j":
```


### Apply the semigroup trick

```{walnut}
%SGT comp_tri3 msd_tri Comp_tri3
```

## 4-abelian complexity

Define the 4-block map of tri and construct the conversion predicate between both numeration systems.

```{walnut}
%%python
s4 = block(s, 4)
ns4 = address(s4, "trib4")
ns4.gen_ns()
(ns-ns4).gen_dfa("conv_tri_trib4")
```

Translate the border condition predicate into the current numeration system.

```{walnut}
def bordercond4 "?msd_trib4 (?msd_tri Eii,jj,kk,nn 
($conv_tri_trib4(?msd_tri ii, ?msd_trib4 i) & 
$conv_tri_trib4(?msd_tri jj, ?msd_trib4 j) & 
$conv_tri_trib4(?msd_tri kk, ?msd_trib4 k) & 
$conv_tri_trib4(?msd_tri nn, ?msd_trib4 n) & 
$bordercond(ii,jj,kk,nn)))":
```

### Compute Parikh vectors

First we compute the Parikh vectors for the prefixes of Trib4.

```{walnut}
%%python
for (i,a) in enumerate(ns4.alpha):
    w = {'_': 0}
    w[a] = 1
    parikh = address(s4, ns4.ns, **w)
    (parikh - ns4).gen_dfa(f"trib4p{i}")
```

### Compute the complexity function

Use Walnut to generate a linear representation for the 4-abelian complexity.

```{walnut}
def fac0 "?msd_trib4 Ex,y $trib4p0(i,x) & $trib4p0(i+n,y) & z+x=y":
def fac1 "?msd_trib4 Ex,y $trib4p1(i,x) & $trib4p1(i+n,y) & z+x=y":
def fac2 "?msd_trib4 Ex,y $trib4p2(i,x) & $trib4p2(i+n,y) & z+x=y":
def fac3 "?msd_trib4 Ex,y $trib4p3(i,x) & $trib4p3(i+n,y) & z+x=y":
def fac4 "?msd_trib4 Ex,y $trib4p4(i,x) & $trib4p4(i+n,y) & z+x=y":
def fac5 "?msd_trib4 Ex,y $trib4p5(i,x) & $trib4p5(i+n,y) & z+x=y":
def fac6 "?msd_trib4 Ex,y $trib4p6(i,x) & $trib4p6(i+n,y) & z+x=y":
def fac7 "?msd_trib4 Ex,y $trib4p7(i,x) & $trib4p7(i+n,y) & z+x=y":
def fac8 "?msd_trib4 Ex,y $trib4p8(i,x) & $trib4p8(i+n,y) & z+x=y":
```

```{walnut}
def min0 "?msd_trib4 Ei $fac0(i,n,x) & Aj,y $fac0(j,n,y) => y>=x":
def min1 "?msd_trib4 Ei $fac1(i,n,x) & Aj,y $fac1(j,n,y) => y>=x":
def min2 "?msd_trib4 Ei $fac2(i,n,x) & Aj,y $fac2(j,n,y) => y>=x":
def min3 "?msd_trib4 Ei $fac3(i,n,x) & Aj,y $fac3(j,n,y) => y>=x":
def min4 "?msd_trib4 Ei $fac4(i,n,x) & Aj,y $fac4(j,n,y) => y>=x":
def min5 "?msd_trib4 Ei $fac5(i,n,x) & Aj,y $fac5(j,n,y) => y>=x":
def min6 "?msd_trib4 Ei $fac6(i,n,x) & Aj,y $fac6(j,n,y) => y>=x":
def min7 "?msd_trib4 Ei $fac7(i,n,x) & Aj,y $fac7(j,n,y) => y>=x":
def min8 "?msd_trib4 Ei $fac8(i,n,x) & Aj,y $fac8(j,n,y) => y>=x":
```

```{walnut}
def diff0 "?msd_trib4 Ex,y $min0(n,x) & $fac0(i,n,y) & z+x=y":
def diff1 "?msd_trib4 Ex,y $min1(n,x) & $fac1(i,n,y) & z+x=y":
def diff2 "?msd_trib4 Ex,y $min2(n,x) & $fac2(i,n,y) & z+x=y":
def diff3 "?msd_trib4 Ex,y $min3(n,x) & $fac3(i,n,y) & z+x=y":
def diff4 "?msd_trib4 Ex,y $min4(n,x) & $fac4(i,n,y) & z+x=y":
def diff5 "?msd_trib4 Ex,y $min5(n,x) & $fac5(i,n,y) & z+x=y":
def diff6 "?msd_trib4 Ex,y $min6(n,x) & $fac6(i,n,y) & z+x=y":
def diff7 "?msd_trib4 Ex,y $min7(n,x) & $fac7(i,n,y) & z+x=y":
def diff8 "?msd_trib4 Ex,y $min8(n,x) & $fac8(i,n,y) & z+x=y":
```

```{walnut}
def abeq_trib4 "?msd_trib4 $bordercond4(i,j,4,n+3) & (Ez $diff0(i,n,z) &  $diff0(j,n,z)) & (Ez $diff1(i,n,z) &  $diff1(j,n,z)) & (Ez $diff2(i,n,z) &  $diff2(j,n,z)) & (Ez $diff3(i,n,z) &  $diff3(j,n,z)) & (Ez $diff4(i,n,z) &  $diff4(j,n,z)) & (Ez $diff5(i,n,z) &  $diff5(j,n,z)) & (Ez $diff6(i,n,z) &  $diff6(j,n,z)) & (Ez $diff7(i,n,z) &  $diff7(j,n,z)) & (Ez $diff8(i,n,z) &  $diff8(j,n,z))":
def abeq_tri4 "?msd_tri (n<3 & $feq_tri(i,j,n)) | (n>=3 & (?msd_trib4 Eii,jj,nn ($conv_tri_trib4(?msd_tri i, ?msd_trib4 ii) & $conv_tri_trib4(?msd_tri j, ?msd_trib4 jj) & $conv_tri_trib4(?msd_tri n, ?msd_trib4 nn) & $abeq_trib4(ii,jj,nn-3))))":
```

```{walnut}
eval comp_tri4 n "?msd_tri Aj $abeq_tri4(i,j,n) => i<=j":
```


### Apply the semigroup trick

```{walnut}
%SGT comp_tri4 msd_tri Comp_tri4
```

## 5-abelian complexity

Define the 5-block map of tri and construct the conversion predicate between both numeration systems.

```{walnut}
%%python
s5 = block(s, 5)
ns5 = address(s5, "trib5")
ns5.gen_ns()
(ns-ns5).gen_dfa("conv_tri_trib5")
```

Translate the border condition predicate into the current numeration system.

```{walnut}
def bordercond5 "?msd_trib5 (?msd_tri Eii,jj,kk,nn 
($conv_tri_trib5(?msd_tri ii, ?msd_trib5 i) & 
$conv_tri_trib5(?msd_tri jj, ?msd_trib5 j) & 
$conv_tri_trib5(?msd_tri kk, ?msd_trib5 k) & 
$conv_tri_trib5(?msd_tri nn, ?msd_trib5 n) & 
$bordercond(ii,jj,kk,nn)))":
```

### Compute Parikh vectors

First we compute the Parikh vectors for the prefixes of Trib5.

```{walnut}
%%python
for (i,a) in enumerate(ns5.alpha):
    w = {'_': 0}
    w[a] = 1
    parikh = address(s5, ns5.ns, **w)
    (parikh - ns5).gen_dfa(f"trib5p{i}")
```

### Compute the complexity function

Use Walnut to generate a linear representation for the 5-abelian complexity.

```{walnut}
def fac0 "?msd_trib5 Ex,y $trib5p0(i,x) & $trib5p0(i+n,y) & z+x=y":
def fac1 "?msd_trib5 Ex,y $trib5p1(i,x) & $trib5p1(i+n,y) & z+x=y":
def fac2 "?msd_trib5 Ex,y $trib5p2(i,x) & $trib5p2(i+n,y) & z+x=y":
def fac3 "?msd_trib5 Ex,y $trib5p3(i,x) & $trib5p3(i+n,y) & z+x=y":
def fac4 "?msd_trib5 Ex,y $trib5p4(i,x) & $trib5p4(i+n,y) & z+x=y":
def fac5 "?msd_trib5 Ex,y $trib5p5(i,x) & $trib5p5(i+n,y) & z+x=y":
def fac6 "?msd_trib5 Ex,y $trib5p6(i,x) & $trib5p6(i+n,y) & z+x=y":
def fac7 "?msd_trib5 Ex,y $trib5p7(i,x) & $trib5p7(i+n,y) & z+x=y":
def fac8 "?msd_trib5 Ex,y $trib5p8(i,x) & $trib5p8(i+n,y) & z+x=y":
def fac9 "?msd_trib5 Ex,y $trib5p9(i,x) & $trib5p9(i+n,y) & z+x=y":
def fac10 "?msd_trib5 Ex,y $trib5p10(i,x) & $trib5p10(i+n,y) & z+x=y":
```

```{walnut}
def min0 "?msd_trib5 Ei $fac0(i,n,x) & Aj,y $fac0(j,n,y) => y>=x":
def min1 "?msd_trib5 Ei $fac1(i,n,x) & Aj,y $fac1(j,n,y) => y>=x":
def min2 "?msd_trib5 Ei $fac2(i,n,x) & Aj,y $fac2(j,n,y) => y>=x":
def min3 "?msd_trib5 Ei $fac3(i,n,x) & Aj,y $fac3(j,n,y) => y>=x":
def min4 "?msd_trib5 Ei $fac4(i,n,x) & Aj,y $fac4(j,n,y) => y>=x":
def min5 "?msd_trib5 Ei $fac5(i,n,x) & Aj,y $fac5(j,n,y) => y>=x":
def min6 "?msd_trib5 Ei $fac6(i,n,x) & Aj,y $fac6(j,n,y) => y>=x":
def min7 "?msd_trib5 Ei $fac7(i,n,x) & Aj,y $fac7(j,n,y) => y>=x":
def min8 "?msd_trib5 Ei $fac8(i,n,x) & Aj,y $fac8(j,n,y) => y>=x":
def min9 "?msd_trib5 Ei $fac9(i,n,x) & Aj,y $fac9(j,n,y) => y>=x":
def min10 "?msd_trib5 Ei $fac10(i,n,x) & Aj,y $fac10(j,n,y) => y>=x":
```

```{walnut}
def diff0 "?msd_trib5 Ex,y $min0(n,x) & $fac0(i,n,y) & z+x=y":
def diff1 "?msd_trib5 Ex,y $min1(n,x) & $fac1(i,n,y) & z+x=y":
def diff2 "?msd_trib5 Ex,y $min2(n,x) & $fac2(i,n,y) & z+x=y":
def diff3 "?msd_trib5 Ex,y $min3(n,x) & $fac3(i,n,y) & z+x=y":
def diff4 "?msd_trib5 Ex,y $min4(n,x) & $fac4(i,n,y) & z+x=y":
def diff5 "?msd_trib5 Ex,y $min5(n,x) & $fac5(i,n,y) & z+x=y":
def diff6 "?msd_trib5 Ex,y $min6(n,x) & $fac6(i,n,y) & z+x=y":
def diff7 "?msd_trib5 Ex,y $min7(n,x) & $fac7(i,n,y) & z+x=y":
def diff8 "?msd_trib5 Ex,y $min8(n,x) & $fac8(i,n,y) & z+x=y":
def diff9 "?msd_trib5 Ex,y $min9(n,x) & $fac9(i,n,y) & z+x=y":
def diff10 "?msd_trib5 Ex,y $min10(n,x) & $fac10(i,n,y) & z+x=y":
```

```{walnut}
def abeq_trib5 "?msd_trib5 $bordercond5(i,j,5,n+4) & (Ez $diff0(i,n,z) &  $diff0(j,n,z)) & (Ez $diff1(i,n,z) &  $diff1(j,n,z)) & (Ez $diff2(i,n,z) &  $diff2(j,n,z)) & (Ez $diff3(i,n,z) &  $diff3(j,n,z)) & (Ez $diff4(i,n,z) &  $diff4(j,n,z)) & (Ez $diff5(i,n,z) &  $diff5(j,n,z)) & (Ez $diff6(i,n,z) &  $diff6(j,n,z)) & (Ez $diff7(i,n,z) &  $diff7(j,n,z)) & (Ez $diff8(i,n,z) &  $diff8(j,n,z)) & (Ez $diff9(i,n,z) &  $diff9(j,n,z)) & (Ez $diff10(i,n,z) &  $diff10(j,n,z))":
def abeq_tri5 "?msd_tri (n<4 & $feq_tri(i,j,n)) | (n>=4 & (?msd_trib5 Eii,jj,nn ($conv_tri_trib5(?msd_tri i, ?msd_trib5 ii) & $conv_tri_trib5(?msd_tri j, ?msd_trib5 jj) & $conv_tri_trib5(?msd_tri n, ?msd_trib5 nn) & $abeq_trib5(ii,jj,nn-4))))":
```

```{walnut}
eval comp_tri5 n "?msd_tri Aj $abeq_tri5(i,j,n) => i<=j":
```


### Apply the semigroup trick

```{walnut}
%SGT comp_tri5 msd_tri Comp_tri5
```
## Check it out!


```{walnut}
%%python
from itertools import product
from ratser.walimp import from_walnut

def valid(a, h, u):
    cur=a
    for c in u:
        v = h[cur]
        if c >= len(v):
            return False
        cur = v[c]
    return True

def enumrepr(a, h, k):
    alpha=list(range(max(map(len,h.values()))))
    for u in product(alpha, repeat=k):
        if valid(a, h, u):
            yield ''.join(map(str,u))

l = []
lbl = []
for k in range(1,6):
    lbl.append(str(k))
    with open(P(os.environ["WALNUT_HOME"]) / P(f"Result/comp_tri{k}.mpl")) as f:
            ser = from_walnut(f)
            l.append(ser)

(a,h)=s.subst()
print(f"{'n':>4}", *[f"{x+'-ab(tri)':>15}" for x in lbl])
print('-'*(4+16*len(lbl)))
for (i, u) in enumerate(enumrepr(a, h, 8)):
    print(f"{i:4}", *[ f"{int(s.value(u)):15}" for s in l ])
```

## Let's wrap it up!

```{walnut}
%%shell
cd $WALNUT_HOME
cat << EOF | tr '\n' '\0' | tar cvzf /tmp/abelian.tar.gz --null -T -
Custom Bases/msd_tri.txt
Custom Bases/msd_tri_addition.txt
Word Automata Library/Tri.txt
Automata Library/feq_tri.txt
Result/comp_tri.mpl
Word Automata Library/Comp_tri1.txt
Result/comp_tri1.mpl
Automata Library/abeq_tri1.txt
Word Automata Library/Comp_tri2.txt
Result/comp_tri2.mpl
Automata Library/abeq_tri2.txt
Word Automata Library/Comp_tri3.txt
Result/comp_tri3.mpl
Automata Library/abeq_tri3.txt
Word Automata Library/Comp_tri4.txt
Result/comp_tri4.mpl
Automata Library/abeq_tri4.txt
Word Automata Library/Comp_tri5.txt
Result/comp_tri5.mpl
Automata Library/abeq_tri5.txt
EOF
```


 {{< downloadthis /tmp/abelian.tar.gz dname="abelian.tar" >}}

